config/routes.rb
WestPartners::Application.routes.draw do
  
  devise_for :users , :skip => :registrations do
  get "/logout" => "devise/sessions#destroy"
  get "/login" => "devise/sessions#new"
  end 
  
  resources :articles
  resources :categories
  resources :contacts
  resources :vacancies
  
  match '/faq', :to => 'pages#faq'

  

  root :to => "pages#home"

end

app/models/vacancy.rb
class Vacancy < ActiveRecord::Base
	belongs_to :category
	has_many :contacts
	
	def previous_vacancy
  		self.class.first(:conditions => ["id < ?", id], :order => "id desc")
	end
	
	def next_vacancy
  		self.class.first(:conditions => ["id > ?", id], :order => "id asc")
	end


end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  before_filter :authenticate_user! , :except => [:index,:show]
  # GET /vacancies
  # GET /vacancies.xml
  def index
    @vacancies = Vacancy.paginate(:page => params[:page],:per_page =>6)
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @vacancies }
    end
  end

  # GET /vacancies/1
  # GET /vacancies/1.xml
  def show
    @vacancy = Vacancy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @vacancy }
    end
  end

  # GET /vacancies/new
  # GET /vacancies/new.xml
  def new
    @vacancy = Vacancy.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @vacancy }
    end
  end

  # GET /vacancies/1/edit
  def edit
    @vacancy = Vacancy.find(params[:id])
  end

  # POST /vacancies
  # POST /vacancies.xml
  def create
    @vacancy = Vacancy.new(params[:vacancy])

    respond_to do |format|
      if @vacancy.save
        format.html { redirect_to(@vacancy, :notice => 'Vacancy was successfully created.') }
        format.xml  { render :xml => @vacancy, :status => :created, :location => @vacancy }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @vacancy.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /vacancies/1
  # PUT /vacancies/1.xml
  def update
    @vacancy = Vacancy.find(params[:id])

    respond_to do |format|
      if @vacancy.update_attributes(params[:vacancy])
        format.html { redirect_to(@vacancy, :notice => 'Vacancy was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @vacancy.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /vacancies/1
  # DELETE /vacancies/1.xml
  def destroy
    @vacancy = Vacancy.find(params[:id])
    @vacancy.destroy

    respond_to do |format|
      format.html { redirect_to(vacancies_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/vacancies/_form.html.erb
<%= javascript_include_tag :ckeditor %>
<%= semantic_form_for(@vacancy) do |f| %>
  <% if @vacancy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vacancy.errors.count, "error") %> prohibited this vacancy from being saved:</h2>

      <ul>
      <% @vacancy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<%= f.inputs do%>
	  <div class="field">
	    <%= f.input :title, :label => "Назва роботи" %><br />
	    <%= f.input :short_desc, :label => "Короткий опис" %><br />
	    <%= f.input :description, :input_html => {:class => 'ckeditor'}, :label => "Опис роботи", :required => false %><br />
	    <%= f.input :price, :label => "Вартість" %><br />
	    <%= f.input :category, :label => "Виберіть категорію" %><br />
	  </div>
	<% end %>
	<div style="margin:0">
	<%= f.buttons do%>
	   <div class="actions">
	    <%= f.commit_button :label => "Створити" %>
	  </div>
	<% end %>
	</div>
<% end %>

app/views/vacancies/edit.html.erb
<h1>Редагувати роботу</h1>

<%= render 'form' %>

app/views/vacancies/index.html.erb
<div style="padding:10px">
	<span class="titletext">Перелік наявних робіт</span>
</div>
<% if user_signed_in? %> 
	<%= link_to 'Додати нову роботу', new_vacancy_path %> 
<% end %>
<div class="bodytext" style="padding:12px;" align="justify">
<% @vacancies.each do |vacancy| %>
    <div id='imgind'>
  		<%= link_to (image_tag(vacancy.category.img_url,:size => "100x100",:alt => vacancy.title)),vacancy %>
  	</div>
  	<div id='titleind'>
  		<strong><%= link_to vacancy.title, vacancy %></strong>
  		<div class='clear'></div>
  			<div id='vacind'>
  				<div align="left" class="smallgraytext"> Вартість: <%= vacancy.price%></div>
  			</div>
  		<div class='clear'></div>
  		<div id='textind'>
	    <%= truncate(vacancy.short_desc,:length => 60, :separator => '') %></br>
	    <%= link_to 'дізнатись більше', vacancy %>
    	</div>
  	</div>
  <% if user_signed_in? %>
    <div class='clear'></div>
    <%= link_to 'Редагувати', edit_vacancy_path(vacancy) %>
    <%= link_to 'Видалити', vacancy, :confirm => 'Are you sure?', :method => :delete %>
  <% end %>
  <div class='line'></div>
<% end %>
	<div align="right" class="smallgraytext" style="padding:9px;">
		<%= will_paginate @vacancies, :previous_label =>"Попередня", :next_label => "Наступна" %>
	</div>
</div>
<br />

app/views/vacancies/new.html.erb
<h1>Нова робота</h1>

<%= render 'form' %>

<%= link_to 'Назад до списку робіт', vacancies_path %>

app/views/vacancies/show.html.erb
<p id="notice"><%= notice %></p>
<div id="submenu">
	<div align="right" class="smallgraytext" style="padding:9px;">
		<%= link_to("Попередня робота |", @vacancy.previous_vacancy) if @vacancy.previous_vacancy %>
		<%= link_to("Наступна робота", @vacancy.next_vacancy) if @vacancy.next_vacancy %>
	</div>
</div>
<div class="bodytext" style="padding:12px;" align="justify">
<div align="center" style="padding:5px;">
	<%= image_tag(@vacancy.category.img_url,:alt => @vacancy.title) %>
</div>
<div class='clear'></div>
<div align="center" style="padding:5px;">
	<strong><%= @vacancy.title %></strong>
  	<div class='clear'></div>
  	<div align="center" class="smallgraytext" style="padding:3px;"> Вартість: <%= @vacancy.price%></div>
</div>
<div class='clear'></div>
<div id='textind'>
	<%=raw @vacancy.description %>
</div>
<div class='clear'></div>
<div class='line'></div>
<div align="left" class="smalltitle" style="padding:9px;">
	Якщо Вас зацікавила дана пропозиція: <%= link_to 'Звяжіться з нами', new_contact_path(:title => @vacancy.title) %> <br />
</div>
</div>