config/routes.rb
WestPartners::Application.routes.draw do
  
  devise_for :users , :skip => :registrations do
  get "/logout" => "devise/sessions#destroy"
  get "/login" => "devise/sessions#new"
  end 
  
  resources :articles
  resources :categories
  resources :contacts
  resources :vacancies
  
  match '/faq', :to => 'pages#faq'

  

  root :to => "pages#home"

end

app/views/layouts/_footer.html.erb
<div id="footer" class="smallgraytext">
		West Partners &copy; 2011 | <%= link_to 'west-partners.com.ua', "http://west-partners.com.ua" %> 
</div>

app/views/layouts/_header.html.erb
<div id="logo"></div>
<div id="topheader">
	<div align="left" class="smallgraytext">
		<br />
		<strong>Кадрове агенство «West Partners»</strong><br />
		м.Самбір, Львівська обл.<br />
		Телефон: +380(097)669-07-62, +380(95)765-06-51<br />
		skype: West-Partners<br />
		e-mail: <%= mail_to "westwork8@gmail.com", "westwork8@gmail.com", :encode => "javascript"%>
	</div>
	<div id="toplinks" class="smallgraytext">
		<%= link_to 'west-partners.com.ua', "http://west-partners.com.ua" %>
		<% if user_signed_in?%>
			<br /><%= link_to 'Запити', contacts_path%>|<%= link_to 'Категорії', categories_path%>|<%= link_to 'Вихід', '/logout'%>
		<% end %>
	</div>
</div>
<div id="menu">
	<div align="right" class="smallwhitetext" style="padding:9px;">
		<%= link_to 'Головна', root_path %> | <%= link_to 'Робота', vacancies_path %> |<%= link_to 'Що потрібно?', '/faq' %> | <%= link_to 'Задати питання', new_contact_path %> 
	</div>
</div>

app/views/layouts/_leftpanel.html.erb
<% @articles=Article.all%>
<div id="leftpanel">
	<div align="left" class="graypanel">
		<% if user_signed_in? %>
		<%= link_to 'Додати статтю', new_article_path %><br />
		<% end %>
		<span class="smalltitle">Статті</span><p>
<% @articles.each do |article| %>
    <span class="smallredtext"><%= article.title %></span><br />
    <span class="bodytextlp"><%=raw truncate(article.content, :length => 115,:separator=>'') %></span><br />
    <span class="smallgraytext"><%= link_to 'детальніше', article %></span><p>
    <% if user_signed_in? %>
    <%= link_to 'Редагувати', edit_article_path(article) %>
    <%= link_to 'Видалити', article, :confirm => 'Ви впевнені що хочете видалити статтю?', :method => :delete %>
    <div class='clear'></div>
    <% end %>
<% end %>
	</div>
</div>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag :all %>
<%= stylesheet_link_tag 'formtastic','style'%>
<!--[if IE 6]><%= stylesheet_link_tag 'formtastic_ie6' %><![endif]-->
<!--[if IE 7]><%= stylesheet_link_tag 'formtastic_ie7' %><![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="uk" lang="uk">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="Robots" content="all" />
	<meta name="author" content="ms" />
	<meta name="West Partners інформаційно- кадрове агенство , яке діє в сфері працевлаштування громадян України , а також громадян СНД за кордоном, зокрема в Польщі." content="Description" />
	<meta name="keywords" content="west-partners,west partners,west-partners.com.ua,www.west-partners.com.ua, робота,робота за кордоном,робота в Польщі,робота закордоном,шукаю роботу в Польщі, пошук роботи закордоном,west partners івано-франківськ,west partners калуш,west partners львів,west partners самбір" />
  <title>West-Partners інформаційно-кадрове агенство , яке діє в сфері працевлаштування громадян України за кордоном, зокрема в Польщі.</title>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-24717907-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body>
    <%- flash.each do |name, msg| -%>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    <%- end -%>
<div id="page" align="center">
		<div id="content" style="width:800px">
		    <%= render 'layouts/header' %>
				<div id="contenttext"><%= yield %></div>
			<%= render 'layouts/leftpanel'%>
			<%= render 'layouts/footer' %>
		</div>
</div>
</body>

</html>